### 데이터 분석을 위한 패키지

In [1]:
## 외부 패키지를 이용해서 원하는 기능을 훨씬 쉽게 작성할 수 있음
## 숫자 데이터를 좀 더 쉽게 다룰수 있도록 도와주는 패키지인 NumbPy와 pandas에 대해 살펴볼 예정

In [2]:
# 배열 데이터를 효과적으로 다루는 Numpy

In [3]:
# Numpy는 파이썬의 내장모듈이 아니므로 별도로 설치해야 이용가능함
# 하지만 아나콘다3에서는 포함돼 있음

In [2]:
import numpy as np

In [3]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2
# 정수와 실수 같이 있을 때 모두 실수로 변환

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [5]:
a1.dtype

dtype('int32')

In [6]:
a2.dtype

dtype('float64')

In [7]:
np.array([0.5, 2, 0.1, 6])

array([0.5, 2. , 0.1, 6. ])

In [8]:
np.array([[1,2,3], [4,5,6], [7,8,9]]) # 다차원 배열도 가능

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
## NumPy의 arange이용 배열 생성
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
## reshape(m,n) 추가 -> m행 x n열 형태의 2차원 배열로 변경할 수 있음
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
b1 = np.arange(12).reshape(4,3)
b1.shape # 배열의 형태를 알기 위해서는 shape 실행

(4, 3)

In [14]:
np.linspace(1,10,4) # 1부터 10까지 4개의 데이터 생성

array([ 1.,  4.,  7., 10.])

In [16]:
np.linspace(0, np.pi, 20) # 0부터 pi까지 동일한 간격으로 나눈 20개의 데이터

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [17]:
np.zeros(10) #원소의 개수가 10개인 0으로 차있는 배열

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones(5) #원소의 개수가 10개인 1으로 차있는 배열

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.eye(3) # n x n의 단위 행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
str_a1 = np.array(["1.567", "0.234", "5.123", "9"])
num_a1 = str_a1.astype(float) # astype은 배열의 형변환
num_a1

array([1.567, 0.234, 5.123, 9.   ])

In [25]:
str_a1.dtype # 문자열 U(유니코드)

dtype('<U5')

In [27]:
num_a1.dtype

dtype('float64')

In [29]:
num_f1 = np.array([10, 21.33, 0.549, 4.65, 5.99])
num_int = num_f1.astype(int)

print(num_int)
print(num_f1.dtype)
print(num_int.dtype)

[10 21  0  4  5]
float64
int32


In [30]:
## np의 난수 배열 생성
np.random.rand(2,3)

array([[0.92300836, 0.57875976, 0.14920754],
       [0.81670905, 0.96458564, 0.12411156]])

In [32]:
np.random.rand()

0.567893943147115

In [33]:
np.random.rand(2,3,4)

array([[[0.90815488, 0.66200094, 0.55793703, 0.04502992],
        [0.93854777, 0.83890484, 0.20301955, 0.42363677],
        [0.01510344, 0.09054729, 0.75867336, 0.57402725]],

       [[0.09957245, 0.73636607, 0.27903582, 0.49001569],
        [0.88073808, 0.17357831, 0.57589777, 0.41119825],
        [0.70738899, 0.96045763, 0.30897689, 0.36556728]]])

In [34]:
np.random.rand(2,3,4,5)

array([[[[0.0226237 , 0.26166024, 0.47366534, 0.4241001 , 0.52741583],
         [0.27655982, 0.3041017 , 0.35749159, 0.01378188, 0.91065363],
         [0.94723657, 0.84050178, 0.41392467, 0.75926827, 0.38344961],
         [0.19009712, 0.90711892, 0.96095485, 0.25823325, 0.98790158]],

        [[0.84920315, 0.18045412, 0.98972378, 0.07491228, 0.3347464 ],
         [0.33939226, 0.97628545, 0.23570366, 0.76623514, 0.35632292],
         [0.85221099, 0.84832466, 0.63634053, 0.19880665, 0.20332368],
         [0.7568802 , 0.69418379, 0.7954232 , 0.69203505, 0.11092174]],

        [[0.81102322, 0.8050067 , 0.3384413 , 0.04382121, 0.11299641],
         [0.84239964, 0.10890468, 0.20527976, 0.40802606, 0.96549498],
         [0.93110044, 0.49407709, 0.61622388, 0.27001045, 0.23561852],
         [0.57393762, 0.02524325, 0.55807605, 0.85316072, 0.53257538]]],


       [[[0.64912221, 0.47576128, 0.59756519, 0.53767537, 0.37048588],
         [0.89467693, 0.23660744, 0.5858811 , 0.08327469, 0.54053854]

In [35]:
np.random.randint(1,30)

20

In [37]:
## 배열의 연산
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [38]:
arr1+arr2

array([11, 22, 33, 44])

In [39]:
arr1-arr2

array([ 9, 18, 27, 36])

In [40]:
arr1 * 2

array([20, 40, 60, 80])

In [41]:
arr1 ** 2

array([ 100,  400,  900, 1600], dtype=int32)

In [42]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [43]:
arr1 / arr2

array([10., 10., 10., 10.])

In [44]:
arr1 > 20

array([False, False,  True,  True])

In [47]:
## 통계를 위한 연산
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [48]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [49]:
[arr3.std(), arr3.var()] # std: 표준편차, var: 분산

[1.4142135623730951, 2.0]

In [50]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [51]:
arr4.cumsum() # 누적 합

array([ 1,  3,  6, 10], dtype=int32)

In [52]:
arr4.cumprod() #누적 곱

array([ 1,  2,  6, 24], dtype=int32)

In [53]:
## 행렬곱 A.dot(B) or np.dot(A,B)
## 전치행렬 A.transpose() 혹은 np.tanspose(A)
## 역행렬 np.linalg.inv(A)
## 행렬식 np.linalg.det(A)

In [55]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [56]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [57]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [59]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [60]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [61]:
np.linalg.det(A)

-2.0

In [64]:
## 배열의 인덱싱과 슬라이싱
arr5 = np.array([0,10,20,30,40,50])
arr5[[1,3,4]] # 여러개의 원소만 선택해서 리스트 구성

array([10, 30, 40])

In [65]:
arr6 = np.arange(10, 100, 10).reshape(3,3)
arr6

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [66]:
arr6[1,2] # 1행, 2열의 숫자는?

60

In [67]:
arr6[2,2] = 95
arr6

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [69]:
arr6[1] # 1행 가져오기

array([40, 50, 60])

In [71]:
arr6[1] = np.array([45, 55, 65])
arr6

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [73]:
arr6[[0,2],[0,1]] # 0,0의 원소, 2,1의 원소로 array 구성

array([10, 80])

In [74]:
arr6[arr6 > 30]

array([45, 55, 65, 70, 80, 95])

In [75]:
## 배열의 슬라이싱(배열의 일부분을 선택)
arr7 = np.array([0,10,20,30,40,50])
arr7[1:4] # 인덱스 1부터 3까지

array([10, 20, 30])

In [76]:
arr7[:3]

array([ 0, 10, 20])

In [77]:
arr7[2:]

array([20, 30, 40, 50])

In [78]:
arr7[2:5] = np.array([25,35,45])
arr7

array([ 0, 10, 25, 35, 45, 50])

In [80]:
arr7[3:6] = 50
arr7

array([ 0, 10, 25, 50, 50, 50])

In [81]:
arr8 = np.arange(10,100,10).reshape(3,3)
arr8

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [82]:
arr8[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [93]:
arr8[1][0:2] # 1행의 0부터 1까지

array([40, 50])

In [94]:
# 구조적 데이터 표시와 처리에 강한 pndas
# NumPy를 기반으로 만들어졌지만 좀 더 복잡한 데이터 분석에 특화돼 있음
# NumPy가 같은 데이터 타입의 배열만 처리할 수 있는 데 반해 pandas는 데이터 타입이 다양하게 섞여 있을 때도 처리 가능

In [95]:
import pandas as pd

In [98]:
s1 = pd.Series([10,20,30,40,50]) #d pandas에서 데이터를 생성하는 기본적인 방법은 Series를 이용(Key와 Value가 있음)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [99]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [101]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [102]:
# Sreies()로 데이터 생성할 때에는 Numpy의 array와 달리 데이터형이 혼합되어 있어도 됨
s2 = pd.Series(["a","b","c", 1,2,3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [103]:
s3 = pd.Series([np.nan, 10, 30]) # np.nan은 데이터가 없다고 표시
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [105]:
# 어느 가게 날짜별 판매량
index_date = ["2018-10-07", "2018-10-08", "2018-10-09", "2018-10-10"]
s4 = pd.Series([200, 195, np.nan, 205], index = index_date) # Index를 지정
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [106]:
s4["2018-10-07"]

200.0

In [108]:
s5 = pd.Series({"국어":100, "영어":95, "수학":97}) # 딕셔너리의 key & values가 각각 index & values로 들어감
s5

국어    100
영어     95
수학     97
dtype: int64

In [4]:
# 날짜 자동 생성
import pandas as pd

pd.date_range(start="2019-01-01", end="2019-02-01") # 날짜 범위 자동생성

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
               '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
               '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
               '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
               '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
               '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01'],
              dtype='datetime64[ns]', freq='D')

In [5]:
pd.date_range(start="2019/01/01", end="2019-02-01")

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
               '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
               '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
               '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
               '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
               '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01'],
              dtype='datetime64[ns]', freq='D')

In [6]:
pd.date_range(start="2019-01-01", periods = 10) # periods로 끝 날짜 지정

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10'],
              dtype='datetime64[ns]', freq='D')

In [13]:
## pd.date_range(start=None, end=None, periods=None, freq = "D")
pd.date_range(start="2019-01-07", periods=4, freq = "2D") # 2일씩 증가

DatetimeIndex(['2019-01-07', '2019-01-09', '2019-01-11', '2019-01-13'], dtype='datetime64[ns]', freq='2D')

In [14]:
pd.date_range(start="2019-01-07", periods=4, freq = "W") # 달력 기준 일주일씩 증가

DatetimeIndex(['2019-01-13', '2019-01-20', '2019-01-27', '2019-02-03'], dtype='datetime64[ns]', freq='W-SUN')

In [15]:
pd.date_range(start="2019-01-07", periods=12, freq = "2BM") # 업무일 기준 2개월 월말 주기로 12개의 날짜 생성

DatetimeIndex(['2019-01-31', '2019-03-29', '2019-05-31', '2019-07-31',
               '2019-09-30', '2019-11-29', '2020-01-31', '2020-03-31',
               '2020-05-29', '2020-07-31', '2020-09-30', '2020-11-30'],
              dtype='datetime64[ns]', freq='2BM')

In [16]:
pd.date_range(start="2019-01-07", periods=4, freq = "QS") # 분기 시작일 기준 4개 날짜

DatetimeIndex(['2019-04-01', '2019-07-01', '2019-10-01', '2020-01-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [17]:
pd.date_range(start="2019-01-07", periods=4, freq = "AS") # 연도의 첫날 기준으로 1년 주기 4개 날짜 생성

DatetimeIndex(['2020-01-01', '2021-01-01', '2022-01-01', '2023-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

In [18]:
pd.date_range(start="2019-01-07 08:00", periods=10, freq = "H") # 1시간 주기로 10개의 시간 생성

DatetimeIndex(['2019-01-07 08:00:00', '2019-01-07 09:00:00',
               '2019-01-07 10:00:00', '2019-01-07 11:00:00',
               '2019-01-07 12:00:00', '2019-01-07 13:00:00',
               '2019-01-07 14:00:00', '2019-01-07 15:00:00',
               '2019-01-07 16:00:00', '2019-01-07 17:00:00'],
              dtype='datetime64[ns]', freq='H')

In [19]:
pd.date_range(start="2019-01-07 08:00", periods=10, freq = "BH") # 업무시간 기준 1시간 주기로 10개의 시간 생성

DatetimeIndex(['2019-01-07 09:00:00', '2019-01-07 10:00:00',
               '2019-01-07 11:00:00', '2019-01-07 12:00:00',
               '2019-01-07 13:00:00', '2019-01-07 14:00:00',
               '2019-01-07 15:00:00', '2019-01-07 16:00:00',
               '2019-01-08 09:00:00', '2019-01-08 10:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [21]:
pd.date_range(start="2019-01-07 08:00", periods=10, freq = "30min") # 30분 단위로 10개의 시간 생성

DatetimeIndex(['2019-01-07 08:00:00', '2019-01-07 08:30:00',
               '2019-01-07 09:00:00', '2019-01-07 09:30:00',
               '2019-01-07 10:00:00', '2019-01-07 10:30:00',
               '2019-01-07 11:00:00', '2019-01-07 11:30:00',
               '2019-01-07 12:00:00', '2019-01-07 12:30:00'],
              dtype='datetime64[ns]', freq='30T')

In [22]:
## DataFrame
## Series는 1차원 데이터, DataFrame은 2차원 데이터, DataFrame으로 구성된 리스트의 새로축은 index, 가로축은 columns
## data의 행 개수와 index 요소 개수, data의 열 개수와 columns 요소 개수는 일치해야 함

pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [23]:
import numpy as np
import pandas as pd

data_list = np.array([[10,20,30],[40,50,60],[70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [24]:
data_list = np.array([[10,20,30],[40,50,60],[70,80,90], [100,110,120]])

index_date = pd.date_range("2019-01-01", periods=4) # data_range로 index 데이터 구성
column_list=["A","B","C"] # columns list 구성

pd.DataFrame(data_list, index = index_date, columns=column_list)

A    B    C
2019-01-01   10   20   30
2019-01-02   40   50   60
2019-01-03   70   80   90
2019-01-04  100  110  120

In [25]:
table_dic = {"연도" : [2015, 2016, 2016, 2017, 2017],
            "지사" : ["한국", "한국", "미국", "한국", "미국"],
            "고객 수" : [200, 250, 450, 300, 500]}

table_dic

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [26]:
pd.DataFrame(table_dic) # 딕셔너리로 한방에 DataFrame 만듦

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [27]:
df1 = pd.DataFrame(table_dic)

df1.mean() # 평균

연도      2016.2
고객 수     340.0
dtype: float64

In [28]:
df1.std() # 표준 편차

연도        0.836660
고객 수    129.421791
dtype: float64

In [35]:
df1.mean(axis=1) # axis가 0이면 열별로 연산 수행, 1이면 행별로 연산 수행

0    1107.5
1    1133.0
2    1233.0
3    1158.5
4    1258.5
dtype: float64

In [36]:
df1.std(axis=1)

0    1283.398808
1    1248.750576
2    1107.329219
3    1214.102343
4    1072.680987
dtype: float64

In [37]:
df1.describe() # 평균, 표준편차, 최솟값, 최댓값 한번에 구할 수 있다!!! 대박사건

연도        고객 수
count     5.00000    5.000000
mean   2016.20000  340.000000
std       0.83666  129.421791
min    2015.00000  200.000000
25%    2016.00000  250.000000
50%    2016.00000  300.000000
75%    2017.00000  450.000000
max    2017.00000  500.000000

In [1]:
import pandas as pd
import numpy as np

KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
           '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
           '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
           '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
           '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017' ]

df_KTX = pd.DataFrame(KTX_data, columns = col_list, index = index_list)
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [3]:
df_KTX.index

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')

In [4]:
df_KTX.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [5]:
df_KTX.values

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

In [6]:
df_KTX.head() # 데이터의 크기가 크면 전체 출력시 너무 많은 데이터가 출력됨, 따라서 Head,tail로 처음 일부분, 끝 일부분 반환

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [7]:
df_KTX.tail() # 인자가 없으면 디폴트는 5

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [8]:
df_KTX.head(2)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN

In [9]:
df_KTX[1:3] # 범위 지정(행 시작위치 ~ 끝위치 -1)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN

In [10]:
df_KTX[2:5] # 범위 지정(행 시작위치 ~ 끝위치 -1)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [14]:
df_KTX.loc["2017"] # index 지정 반환

경부선 KTX    32427.0
호남선 KTX     9228.0
경전선 KTX     5570.0
전라선 KTX     5766.0
동해선 KTX     6667.0
Name: 2017, dtype: float64

In [15]:
df_KTX.loc["2013":"2016"]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0

In [19]:
df_KTX["경부선 KTX"] # DataFrame["column_name"] 해당 열 데이터 반환

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64

In [20]:
df_KTX["경부선 KTX"]["2012":"2014"] # Column, index 이름으로 출력

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64

In [21]:
df_KTX["경부선 KTX"][2:5] # index 위치로 범위 지정

2013    42005
2014    43621
2015    41702
Name: 경부선 KTX, dtype: int64

In [22]:
df_KTX["경부선 KTX"][2]

42005

In [23]:
df_KTX["호남선 KTX"]["2016"]

10622

In [24]:
## DataFrame[column_name][index_name]
## DataFrame[column_name][index_position]
## DataFrame.loc[index_name][column_name]
## DataFrame.loc[index_name, column_name]

In [26]:
df_KTX.loc["2016"]["동해선 KTX"]

3786.0

In [27]:
df_KTX.loc["2016", "동해선 KTX"]

3786.0

In [28]:
df_KTX.T # 전치 구하기 T (행과 열이 뒤바뀜)

2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0

In [29]:
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [35]:
df_KTX[["동해선 KTX", "전라선 KTX", "호남선 KTX", "경부선 KTX", "경전선 KTX"]] # 열의 항목 순서 변경

동해선 KTX  전라선 KTX  호남선 KTX  경부선 KTX  경전선 KTX
2011      NaN      309     7313    39060     3627
2012      NaN     1771     6967    39896     4168
2013      NaN     1954     6873    42005     4088
2014      NaN     2244     6626    43621     4424
2015   2395.0     3146     8675    41702     4606
2016   3786.0     3945    10622    41266     4984
2017   6667.0     5766     9228    32427     5570

In [40]:
## 데이터 통합하기 (append(), join() 이용)
# 먼저 세로 방향으로 통합하기(append())
mydic = {"Class1": [95,92,96,94], "Class2" : [66,77,82,34]}
df1 = pd.DataFrame(mydic)
df1

Class1  Class2
0      95      66
1      92      77
2      96      82
3      94      34

In [41]:
mydic = {"Class1": [11,22], "Class2" : [33,44]}
df2 = pd.DataFrame(mydic)
df2

Class1  Class2
0      11      33
1      22      44

In [42]:
df1.append(df2) # 추가된 df2의 인덱스는 그대로
# 열의 이름은 일치해야함

Class1  Class2
0      95      66
1      92      77
2      96      82
3      94      34
0      11      33
1      22      44

In [44]:
df1.append(df2, ignore_index=True) # 추가된 df2의 인덱스는 df1 형식

Class1  Class2
0      95      66
1      92      77
2      96      82
3      94      34
4      11      33
5      22      44

In [48]:
df3 = pd.DataFrame({"Class1":[24, 67]})
df1.append(df3)

Class1  Class2
0      95    66.0
1      92    77.0
2      96    82.0
3      94    34.0
0      24     NaN
1      67     NaN

In [49]:
df1.append(df3, ignore_index=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


Class1  Class2
0      95    66.0
1      92    77.0
2      96    82.0
3      94    34.0
4      24     NaN
5      67     NaN

In [50]:
# 가로방향으로 통합하기(join())
df4 = pd.DataFrame({"Class3":[21,32,43,54]})
df4

Class3
0      21
1      32
2      43
3      54

In [52]:
df1.join(df4) # 두 데이터의 index 개수, 이름이 일치해야 함

Class1  Class2  Class3
0      95      66      21
1      92      77      32
2      96      82      43
3      94      34      54

In [55]:
index_lable = ["a","b","c","d"]

df5 = pd.DataFrame({"Class1":[1,2,3,4], "Class2":[6,7,8,9]}, index=index_lable )
df6 = pd.DataFrame({"Class3":[1,2,3,4]}, index=index_lable)

df5.join(df6)  # index 동일해야 함

Class1  Class2  Class3
a       1       6       1
b       2       7       2
c       3       8       3
d       4       9       4

In [56]:
df7 = pd.DataFrame({"Class4" : [23,54]})

df1.join(df7)

Class1  Class2  Class4
0      95      66    23.0
1      92      77    54.0
2      96      82     NaN
3      94      34     NaN

In [11]:
## 특정 열을 기준으로 통합하기
df_A_B = pd.DataFrame({"판매월":["1월", "2월", "3월", "4월"], "제품 A":[100, 150, 200, 120], "제품 B" : [90, 110, 140, 170]})
df_A_B

판매월  제품 A  제품 B
0  1월   100    90
1  2월   150   110
2  4월   200   140
3  7월   120   170

In [12]:
df_C_D = pd.DataFrame({"판매월":["1월", "2월", "3월", "4월"], "제품 C":[13,24,35,46], "제품 D" : [52,66,78,81]})
df_C_D

판매월  제품 C  제품 D
0  1월    13    52
1  2월    24    66
2  3월    35    78
3  4월    46    81

In [13]:
df_A_B.merge(df_C_D) # 공통된 Column을 key로 통합

판매월  제품 A  제품 B  제품 C  제품 D
0  1월   100    90    13    52
1  2월   150   110    24    66
2  4월   200   140    46    81

In [5]:
import pandas as pd

df_left = pd.DataFrame({"key":["A","B","C","D"], "left":[1,2,3,4]})
df_left

key  left
0   A     1
1   B     2
2   C     3
3   D     4

In [7]:
df_right = pd.DataFrame({"key":["A","B","D","E"], "right":[5,6,7,8]})
df_right

key  right
0   A      5
1   B      6
2   D      7
3   E      8

In [9]:
df_left.merge(df_right)

key  left  right
0   A     1      5
1   B     2      6
2   D     4      7

In [15]:
# how 인자 - left: 왼쪽 데이터 모두 선택, 지정된 열에 값이 있는 오른쪽 데이터 선택, right는 반대, 
# outer: 지정된 열을 기준으로 왼쪽과 오른쪽 데이터 모두 선택, inner: 지정된 열을 기준으로 왼쪽, 오른쪽 데이터 중 공통 항목만 선택(기본값)

df_left.merge(df_right, how="left", on = "key")

key  left  right
0   A     1    5.0
1   B     2    6.0
2   C     3    NaN
3   D     4    7.0

In [16]:
df_left.merge(df_right, how="right", on = "key")

key  left  right
0   A   1.0      5
1   B   2.0      6
2   D   4.0      7
3   E   NaN      8

In [17]:
df_left.merge(df_right, how="outer", on = "key")

key  left  right
0   A   1.0    5.0
1   B   2.0    6.0
2   C   3.0    NaN
3   D   4.0    7.0
4   E   NaN    8.0

In [18]:
df_left.merge(df_right, how="inner", on = "key")

key  left  right
0   A     1      5
1   B     2      6
2   D     4      7

In [19]:
## 데이터 파일 읽고 쓰기
# csv(comma seperated value ) 파일 읽기

In [25]:
%%writefile C:\Users\GroundPark\Documents\Jupyter\data\sea_rain1.csv
    연도, 동해, 남해, 서해, 전체
    1996, 17.4629, 17.2288, 14.436, 15.9067
    1997, 17.4116, 17.4092, 14.8248, 16.1526
    1998, 17.5435, 17.1324, 14.879, 16.4564
    1999, 18.1495, 18.1234, 14.879, 16.9754
    2000, 17.935,  18.8904, 15.0504, 16.6178

Overwriting C:\Users\GroundPark\Documents\Jupyter\data\sea_rain1.csv


In [32]:
pd.read_csv("C:/Users/GroundPark/Documents/Jupyter/data/sea_rain1.csv")

연도       동해       남해       서해       전체
0    1996  17.4629  17.2288  14.4360  15.9067
1    1997  17.4116  17.4092  14.8248  16.1526
2    1998  17.5435  17.1324  14.8790  16.4564
3    1999  18.1495  18.1234  14.8790  16.9754
4    2000  17.9350  18.8904  15.0504  16.6178

In [33]:
## 파이썬에서 텍스트 파일을 생성하면 기본 문자 인코딩 형식이 utf-8, 하지만 윈도우의 메모장에서 파일을 저장하면 인코딩 형식이
## cp949가 됨, pandas의 read_csv()로 csv 파일을 읽어 올 때 텍스트 파일의 인코딩 형식에 따라 옵션을 지정해야 함
## 그렇지 않으면 한글을 제대로 표현할 수 없음

In [34]:
%%writefile C:\Users\GroundPark\Documents\Jupyter\data\sea_rain1_space.txt
    연도 동해 남해 서해 전체
    1996 17.4629 17.2288 14.436 15.9067
    1997 17.4116 17.4092 14.8248 16.1526
    1998 17.5435 17.1324 14.879 16.4564
    1999 18.1495 18.1234 14.879 16.9754
    2000 17.935  18.8904 15.0504 16.6178

Overwriting C:\Users\GroundPark\Documents\Jupyter\data\sea_rain1_space.txt


In [44]:
pd.read_csv("C:/Users/GroundPark/Documents/Jupyter/data/sea_rain1_space.txt", sep=",") # 공백으로 구분하는건 sep=" "인데 안먹힌다;;

연도 동해 남해 서해 전체
0       1996 17.4629 17.2288 14.436 15.9067
1      1997 17.4116 17.4092 14.8248 16.1526
2       1998 17.5435 17.1324 14.879 16.4564
3       1999 18.1495 18.1234 14.879 16.9754
4      2000 17.935  18.8904 15.0504 16.6178

In [46]:
# 표 형식의 데이터를 파일로 쓰기
df_WH = pd.DataFrame({"Weight":[62,78,88,67], "Height":[165,177,180,175]}, index=["ID_1", "ID_2", "ID_3", "ID_4"])
df_WH.index.name = "User"
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      78     177
ID_3      88     180
ID_4      67     175

In [47]:
bmi = df_WH["Weight"] / (df_WH["Height"]/100)**2
bmi

User
ID_1    22.773186
ID_2    24.897060
ID_3    27.160494
ID_4    21.877551
dtype: float64

In [48]:
df_WH["BMI"] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      78     177  24.897060
ID_3      88     180  27.160494
ID_4      67     175  21.877551

In [52]:
df_WH.to_csv("C:/Users/GroundPark/Documents/Jupyter/data/save_DataFrame.csv")

In [56]:
!type C:\Users\GroundPark\Documents\Jupyter\data\save_DataFrame.csv

User,Weight,Height,BMI
ID_1,62,165,22.77318640955005
ID_2,78,177,24.897060231734173
ID_3,88,180,27.160493827160494
ID_4,67,175,21.877551020408163
